### ISSUE TITLE
Issue with release 0.1.2

### ISSUE THREAD

**Issue by bazzadp** [othree/smartypants.js#11]
Getting this with the new version released last night:

```
Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "smartypants.js" defined in the package config ......./src/node_modules/smartypants/package.json; targets must start with "./"
    at new NodeError (node:internal/errors:329:5)
    at throwInvalidPackageTarget (node:internal/modules/esm/resolve:356:9)
    at resolvePackageTargetString (node:internal/modules/esm/resolve:384:5)
    at resolvePackageTarget (node:internal/modules/esm/resolve:421:12)
    at resolvePackageTarget (node:internal/modules/esm/resolve:467:26)
    at packageExportsResolve (node:internal/modules/esm/resolve:522:22)
    at resolveExports (node:internal/modules/cjs/loader:473:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:513:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:910:27)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
Error: Process completed with exit code 1.
```

I presume these lines:

https://github.com/othree/smartypants.js/blob/3e8d164fc4993dc1ba818e3119e94639ec0ab573/package.json#L8-L12

Should actually be:

```json
"exports": {
    ".": {
        "import": "./smartypants.es6.js",
        "require": "./smartypants.js"
    }
```

Similar to the `bin` lines further down?

This is on node v14

**Comment by othree** [comment]
Thank you, please try 0.1.3

**Comment by bazzadp** [comment]
Now getting a different error:

```
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/barry/almanac.httparchive.org/src/node_modules/smartypants/smartypants.js
require() of ES modules is not supported.
require() of /Users/barry/almanac.httparchive.org/src/node_modules/smartypants/smartypants.js from /Users/barry/almanac.httparchive.org/src/tools/generate/generate_typographic_punctuation.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename smartypants.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/barry/almanac.httparchive.org/src/node_modules/smartypants/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/barry/almanac.httparchive.org/src/tools/generate/generate_typographic_punctuation.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by othree** [comment]
Removed "type": "module". Please try 0.1.4.

**Comment by bazzadp** [comment]
Looks good now! Thanks for all your efforts!

**Comment by bazzadp** [comment]
Actually don't think it's right, and think it's a bug with the original fix to #9.

It generates fine now, but is using the wrong smart quotes for opening quotes following by an 's' for example:

`It effectively &#8220;skips&#8221; over all navigational`

should be:

`It effectively &#8221;skips&#8221; over all navigational`

**Comment by othree** [comment]
Wow, I used the wrong regexp syntax for a long time. Not sure how it could work for most cases for such a long time. 0.1.5 release.

**Comment by bazzadp** [comment]
Looks good now thanks! And yes it did fix some other ones too that I'd never even noticed was were wrong!
